### ISSUE TITLE
Documentation class hierarchy diagram svg is missing

### ISSUE THREAD

**Issue by FlickerBean** [yale-web-technologies/IIIF-Manifest-Generator#2]
Not hugely urgent. But `docs/graphs/classes.svg` is missing from the repository.

**Comment by hshyk** [comment]
Seems to be related to [#1047](https://github.com/phpDocumentor/phpDocumentor2/issues/1047). I used a Docker container which most likely did not have GraphViz installed. I will look at regenerating.

**Comment by hshyk** [comment]
Added the missing classes.svg file.
