### ISSUE TITLE
BUG: A manifest with multiple sequences can never validate.

### ISSUE THREAD

**Issue by FlickerBean** [yale-web-technologies/IIIF-Manifest-Generator#3]
At present validation requires that all sequences contain a canvas. It also specifies that in a manifest a sequence after the first one may only contain 'id', 'type' and 'label'.

Unless i'm doing something wrong, the 'isTopLevel' property appears to have no effect on either of these requirements, making the circular logic impossible to follow.
 
~~I believe that for this to work in `Resources/Sequence.php` the 'Canvases must be present in a sequence' requirement needs moving into the 'isTopLevel' clause?~~

-----------------------

I think the fix for this is to add a `memberDataOnly` clause to the top of the `sequence::toArray` method:

```
         if ($this->getOnlyMemberData()) {
            ArrayCreator::addRequired($item, Identifier::ID, $this->getID(), "The id must be present in a Manifest");
            ArrayCreator::addRequired($item, Identifier::TYPE, $this->getType(), "The type must be present in a Manifest");
            ArrayCreator::addRequired($item, Identifier::LABEL, $this->getLabels(), "The label must be present in a Manifest");

            return $item;
        }

```

Then add `getOnlyMemberData` to the manifest::validateSequence exclusions:

```
    public function validateSequence(Sequence $sequence)
    {
        $classname = '\IIIF\PresentationAPI\Resources\Sequence';
        $exclusions = array(
            'getID',
            'getType',
            'getLabels',
            'getDefaultContext',
            **'getOnlyMemberData'**
        );
        $message = "A Sequence after the first one embedded within a Manifest should only contain an id, type and label";
        Validator::shouldNotContainItems($sequence, $classname, $exclusions, $message);
        Validator::shouldContainItems($sequence, array('getLabels'), 'Multiple Sequences within a Manifest must contain a label');
    }
```

And then for ease of use we can automate setting onlyMemberData on every sequence after the first in manifest.php:

```
    /**
     * Add a sequence to the manifest.
     *
     * @param \IIIF\PresentationAPI\Resources\Sequence $sequence
     */
    public function addSequence(Sequence $sequence)
    {
        if (count($this->sequences)) {
            $sequence->returnOnlyMemberData();
        }
        array_push($this->sequences, $sequence);
    }

```

If i'm misunderstanding something please let me know.

**Comment by hshyk** [comment]
This makes sense, since it should force all sequences after the first to only contain member data. My usage of isTopOnly is just to set the context in this instance and not connected to the sequence count.

If you would like, you can submit a PR. Otherwise I can update. The only change i would do from you code above would be to change 

`if (count($this->sequences)) {`

to 

`if (count($this->sequences) > 1) {`

**Comment by FlickerBean** [comment]
I'm happy to submit a PR however it may have to wait a day or two.

I think changing

`if  (count($this->sequences)) {`

to

`if (count($this->sequences) > 1) {`

would only only set `onlyReturnMemberData` on the 3rd+ sequence added to the manifest, as the test is being performed before the current sequence is added to the sequences property. In other words, there would have to be 2 sequences already in the manifest before the statement evaluates to true and starts setting `onlyReturnMemberData` on the successive sequences. If that makes any sense?

**Comment by hshyk** [comment]
Sorry, my mistake, I was actually thinking greater than or equals. That way, for readability, you know you are checking for something after the first element. It's just semantics, either way should be fine.

`if (count($this->sequences) >= 1) {`
