### ISSUE TITLE
Error in README.md Example?

### ISSUE THREAD

**Issue by tobiashreiter** [yale-web-technologies/IIIF-Manifest-Generator#6]
In the 10th line of the example, should 

` $thumbnail->setService($service_thumbnail);`

actually be

 `$manifest->setService($service_thumbnail);`

This is a really cool library -- hoping to use it for our organization's IIIF implementation.

**Comment by hshyk** [comment]
@tobiashreiter Thank you for catching that!  The piece that was missing was actually instantiating the thumbnail library.  This is based of off the documentation example in: http://iiif.io/api/presentation/2.1/#manifest.  To add a service in a manifest, it would be: 
```PHP
$manifest->addService(...)
```

I am excited that you want to use it!  Would you be willing to message or email me how/where you intend to implement it?

**Comment by tobiashreiter** [comment]
Thanks for your clarification – I’ll have a look at the IIIF documentation to get a better idea of how this all comes together. I’m still confused about the $thumbnail instance gets attached to the $manifest.

We’re still quite a way off from our implementation of IIIF. Our site uses a mix of PHP and Node – right now we use METS to drive an older viewer implementation on the Node server. If we take the route of PHP-based generated manifests, your library looks like a good approach (I’d rather build this up in a structured way then just manually build the JSON from scratch).

Thanks again for such prompt attention to my issue.

Regards,
Toby Reiter

--
Toby Reiter | Web developer
Archives of American Art | Smithsonian Institution
T 202.633.7968<tel:202.633.7968> | F 202.633.7994<tel:202.633.7994> | GV 202.630.2184<tel:202.630.2184>
www.aaa.si.edu<http://www.aaa.si.edu/>| blog.aaa.si.edu<http://blog.aaa.si.edu/>

DC Headquarters
FedEx/UPS/DHL: 750 9th Street NW | Suite 2200 | Washington, DC 20001
USPS: PO Box 37012, Victor Building 2200 | MRC 937 | Washington, DC 20013-7012

New York Office
300 Park Avenue South | Suite 300 | New York, NY 10010

Join us on Facebook<https://www.facebook.com/archivesofamericanart> | Twitter<https://twitter.com/ArchivesAmerArt> | Tumblr<http://archivesofamericanart.tumblr.com/> | Pinterest<http://www.pinterest.com/archivesamerart/> | Instagram<http://instagram.com/archivesamerart>

**Comment by hshyk** [comment]
I missed a line in the README.md (added in now): 
```PHP  
$manifest->addThumbnail($thumbnail);
```
You can also add more than 1 thumbnail into the manifest.

This library came out of the [Ten Thousand Rooms Project](https://tenthousandrooms.yale.edu/) at Yale.  This is a Drupal site where users are able to create their [own projects and pages](https://tenthousandrooms.yale.edu/projects). On creation, that content then gets turned into a manifest file programmatically. The manifest file is then read by the Mirador viewer. It would not have been practical to hand generate any JSON files.

**Comment by tobiashreiter** [comment]
Thanks for sending on the link to the project. It’s really quite incredible what people were able to do with the site.

--
Toby Reiter | Web developer
Archives of American Art | Smithsonian Institution
T 202.633.7968<tel:202.633.7968> | F 202.633.7994<tel:202.633.7994> | GV 202.630.2184<tel:202.630.2184>
www.aaa.si.edu<http://www.aaa.si.edu/>| blog.aaa.si.edu<http://blog.aaa.si.edu/>

DC Headquarters
FedEx/UPS/DHL: 750 9th Street NW | Suite 2200 | Washington, DC 20001
USPS: PO Box 37012, Victor Building 2200 | MRC 937 | Washington, DC 20013-7012

New York Office
300 Park Avenue South | Suite 300 | New York, NY 10010

Join us on Facebook<https://www.facebook.com/archivesofamericanart> | Twitter<https://twitter.com/ArchivesAmerArt> | Tumblr<http://archivesofamericanart.tumblr.com/> | Pinterest<http://www.pinterest.com/archivesamerart/> | Instagram<http://instagram.com/archivesamerart>

**Comment by hshyk** [comment]
Yeah, it's really interesting. The real claim to fame is the ability to add annotations. My colleague @gigamorph forked Mirador for our use and then we had another team member build an annotation server in Rails.  Users can annotate any project they are a member of (example: https://tenthousandrooms.yale.edu/node/311/mirador?canvas=14116).

FYI, feel free to register for the site, create some projects, pages, images, etc and then annotate on them.

**Comment by tobiashreiter** [comment]
The annotation is really remarkable – I particularly was looking at the “a Variorum Story of the Stone” project. The multiple layers of annotation add a lot of possibilities (although it would be easier if the annotation colors matched the color in the drop down menu).

Just today (in fact between the last email I sent and this one), we had a meeting that discussed the possibility of crowdsourcing transcription and image description within the context of our site. This would be one possibility for providing that service

Is the Rails annotations code also open source?

Thanks,
Toby

--
Toby Reiter | Web developer
Archives of American Art | Smithsonian Institution
T 202.633.7968<tel:202.633.7968> | F 202.633.7994<tel:202.633.7994> | GV 202.630.2184<tel:202.630.2184>
www.aaa.si.edu<http://www.aaa.si.edu/>| blog.aaa.si.edu<http://blog.aaa.si.edu/>

DC Headquarters
FedEx/UPS/DHL: 750 9th Street NW | Suite 2200 | Washington, DC 20001
USPS: PO Box 37012, Victor Building 2200 | MRC 937 | Washington, DC 20013-7012

New York Office
300 Park Avenue South | Suite 300 | New York, NY 10010

Join us on Facebook<https://www.facebook.com/archivesofamericanart> | Twitter<https://twitter.com/ArchivesAmerArt> | Tumblr<http://archivesofamericanart.tumblr.com/> | Pinterest<http://www.pinterest.com/archivesamerart/> | Instagram<http://instagram.com/archivesamerart>

**Comment by hshyk** [comment]
Here is the annotation server: https://github.com/yale-web-technologies/mirador-annotations. The associated forked Mirador is here: https://github.com/yale-web-technologies/yale-mirador.  I would contact @gigamorph as he is more knowledgeable about their implementations.

**Comment by tobiashreiter** [comment]
Thanks!

--
Toby Reiter | Web developer
Archives of American Art | Smithsonian Institution
T 202.633.7968<tel:202.633.7968> | F 202.633.7994<tel:202.633.7994> | GV 202.630.2184<tel:202.630.2184>
www.aaa.si.edu<http://www.aaa.si.edu/>| blog.aaa.si.edu<http://blog.aaa.si.edu/>

DC Headquarters
FedEx/UPS/DHL: 750 9th Street NW | Suite 2200 | Washington, DC 20001
USPS: PO Box 37012, Victor Building 2200 | MRC 937 | Washington, DC 20013-7012

New York Office
300 Park Avenue South | Suite 300 | New York, NY 10010

Join us on Facebook<https://www.facebook.com/archivesofamericanart> | Twitter<https://twitter.com/ArchivesAmerArt> | Tumblr<http://archivesofamericanart.tumblr.com/> | Pinterest<http://www.pinterest.com/archivesamerart/> | Instagram<http://instagram.com/archivesamerart>
